version: "3.8"

x-healthcheck-defaults: &healthcheck_defaults
  interval: 10s  # 间隔
  timeout: 5s  # 超时
  retries: 5  # 连续失败次数
  start_period: 10s # 初始化时间

services:

  guide:
    container_name: guide
    image: general9527/guide:latest
    ports:
      - "9999:9999"
    volumes:
      - ./guide/configs:/opt/configs
      - ./guide/logs/:/opt/logs/
      - ./guide/assets/upload/:/opt/assets/upload
      - ./guide/lock/:/opt/lock
    networks:
      - guide
    healthcheck:
      test: "/bin/netstat -anpt|grep 9999"
      <<: *healthcheck_defaults
    depends_on:
      guide-mysql:
        condition: service_healthy
      guide-redis:
        condition: service_healthy


  guide-mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: guide
      TZ: Asia/Shanghai
      # 允许来自其他主机的根连接
      # https://dev.mysql.com/doc/refman/5.7/en/docker-mysql-more-topics.html#docker_var_mysql-root-host
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - guide
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      <<: *healthcheck_defaults


  guide-redis:
    image: redis:6.2.4
    container_name: guide-redis
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    networks:
      - guide
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      <<: *healthcheck_defaults

networks:
  guide:
    driver: bridge
    name: guide
